package it.polimi.ingsw.Constants;

public enum MessageType {
    CORRECT_INPUT("CORRECT INPUT"),
    NOT_VALID_INPUT("NOT VALID INPUT"),
    NOT_VALID_INDEX("NOT VALID INDEX"),
    ALREADY_PLAYED("ALREADY PLAYED"),
    ALREADY_PLAYED_THIS_TURN("ALREADY PLAYED THIS TURN"),
    PRINT_ALL_ISLANDS("PRINT ALL ISLANDS"),
    PRINT_ISLAND("PRINT ISLAND"),
    PRINT_ALL_BOARDS("PRINT ALL BOARDS"),
    PRINT_BOARD("PRINT BOARD"),
    PRINT_TEACHERS("PRINT TEACHERS"),
    PRINT_ALL_CLOUDS("PRINT CLOUDS"),
    PRINT_ASSISTANT_CARDS("PRINT ASSISTANT CARDS"),
    PRINT_CHARACTER_CARDS("PRINT CHARACTER CARDS"),
    EASY_MESSAGE("EASY MESSAGE");

    private final String type;

    MessageType(String type) {
        this.type = type;
    }

    public String getType() {
        return type;
    }
}
