package it.polimi.ingsw.Constants;

public enum MessageType {
    CORRECT_INPUT,
    NOT_VALID_INPUT,
    NOT_VALID_INDEX,
    ALREADY_PLAYED,
    ALREADY_PLAYED_THIS_TURN,
    PRINT_ALL_ISLANDS,
    PRINT_ISLAND,
    PRINT_ALL_BOARDS,
    PRINT_BOARD,
    PRINT_TEACHERS,
    PRINT_ALL_CLOUDS,
    PRINT_ASSISTANT_CARDS,
    PRINT_CHARACTER_CARDS,
    EASY_MESSAGE
}
